### ISSUE TITLE
Can you help me to setup your model with my data ?

### ISSUE THREAD

**Issue by AliD201** [markadivalerio/audio-classifier-project#2]
Greetings, 
Hope you have a nice day, i am working on an audio classification project which i have to distinguish between very similar sounds so i thought about your approach of using the multiple futures  but didn't know how, so far i used only mel-spectgrom and barely got a 32% error rate with image classification (using fastai)
so i want to try your model with my data if that is possible but, i didn't understand the code that much.

i wish to contact you in order to help me setup the code, here is my discord 
(Artist201#5802) 
hope to meet you as soon as possible 
Thank you.

**Comment by markadivalerio** [comment]
So grabbing the data was a bit tricky and difficult, what I did is once i had the data, i put 187 attributes / audio features that i could pull and stored it into the  `/data/all_data_*.npy` and `/data/all_labels_*.npy` files...then you can perform a load of just the attributes with np.load(), instead of extracting the audio attributes of the raw .wav files each and every run (which could take 15ish min per run, depending on your computer)

if that doesn't work for ya let me know (and if not, what did you try to do. There is a separate README file in the /scripts folder with instructions on downloading the data - may need slight tweaking)

**Comment by AliD201** [comment]
i am trying to use my data not the available data, it is a different data set that i recorded where i have the raw wav files in my system .
so i was trying to load my data into your model .
if i am not mistaken all i need is to edit your  **load_all_wav_files** function inorder to input my data, into your model right ? ( and i am not sure how to do that )
i am currently following the **audio-classifier-project.ipynb** which seems to be the full program.

**Comment by AliD201** [comment]
i was able to run it , Thanks !
